Repository SE-UUlm/snowballr-api, pull requests merged in 2025-05, with the labels that each got.

#24 feat: add methods to get next and previous paper
  .gitignore
  proto/main.proto
  proto/project.proto
Labels: enhancement

#25 feat: add mermaid support to sabledocs
  Dockerfile
  patches/markdown_mermaidjs_no_script.patch
  patches/sabledocs_fix_nested.patch
  patches/sabledocs_mermaid_theme_change.patch
  sabledocs.toml
Labels: enhancement

#28 Add Build And Run Recipes To Justfile
  Justfile
Labels: enhancement

#30 Rename Issue Template `.yaml` Files to `.yml` as Github Seems to Have Trouble with the Former
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactor_request.yml
Labels: bug

#27 ER Diagram
  proto/main.proto
Labels: documentation

#32 Fix Issue When Multiple Mermaid Figures are in the Same Document
  patches/sabledocs_mermaid_theme_change.patch
Labels: bug, documentation

#33 Fix List Styling for Unordered Lists
  Dockerfile
  patches/sabledocs_styles.patch
Labels: documentation
